"""
Emit the demo corpus as loadable PostgreSQL SQL and MongoDB JavaScript.

The demo database containers seed themselves from these files through
`docker-entrypoint-initdb.d`, the same mechanism the integration test stack
uses. Generating files rather than connecting directly keeps this step free of
database drivers and makes the seed inspectable before it is applied.

Chunking reuses `src.preprocessing.chunking`, so demo chunks are produced by
exactly the same code as the ML evaluation chunks -- the chunk boundaries the
embeddings are built on cannot drift between the two.

Usage:
    python -m src.demo.emit --out ../DBE-DSD/database/demo
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from src.demo.corpus import DEFAULT_PER_TOPIC, DEFAULT_SEED, generate
from src.demo.topics import CATEGORIES
from src.preprocessing.chunking import chunk_document

# bcrypt hash of "demopass123" -- demo environment only, never a deployed
# credential. Generated once and fixed so the seed stays deterministic.
DEMO_PASSWORD_HASH = "$2a$10$.qLHFgbEflNqmlMhgu5uJe5YJWkOCzOCTso6kq53N7c0arzlwQTyW"


def sql_quote(value: str) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def emit_postgres(corpus, path: Path) -> None:
    lines = [
        "-- Synthetic enterprise demo corpus.",
        "-- DEMO ENVIRONMENT ONLY. Generated by subjects/ML/src/demo/emit.py --",
        "-- do not hand-edit, and do not load into the integration test stack:",
        "-- the 55 regression tests pin exact document counts and ids.",
        "-- Every user below shares the bcrypt hash of 'demopass123'.",
        "",
        "BEGIN;",
        "",
        "-- Categories (idempotent: the base schema may already define them)",
    ]
    for name in CATEGORIES:
        lines.append(
            f"INSERT INTO categories (name, description) VALUES "
            f"({sql_quote(name)}, {sql_quote(name + ' documents')}) "
            f"ON CONFLICT DO NOTHING;"
        )

    lines += ["", "-- Users"]
    for user in corpus.users:
        lines.append(
            "INSERT INTO users (username, email, password_hash, full_name) VALUES ("
            f"{sql_quote(user['username'])}, {sql_quote(user['email'])}, "
            f"{sql_quote(DEMO_PASSWORD_HASH)}, {sql_quote(user['full_name'])});"
        )

    lines += ["", "-- Roles for demo users"]
    for user in corpus.users:
        lines.append(
            "INSERT INTO user_roles (user_id, role_id) SELECT u.id, r.id FROM users u, roles r "
            f"WHERE u.username = {sql_quote(user['username'])} AND r.name = {sql_quote(user['role'])};"
        )

    lines += ["", "-- Documents"]
    for document in corpus.documents:
        lines.append(
            "INSERT INTO documents (id, title, description, category_id, owner_id, "
            "storage_reference, document_type, status) SELECT "
            f"{document['document_id']}, {sql_quote(document['title'])}, "
            f"{sql_quote(document['description'])}, c.id, u.id, "
            f"{sql_quote(document['storage_reference'])}, "
            f"{sql_quote(document['document_type'])}, {sql_quote(document['status'])} "
            f"FROM categories c, users u WHERE c.name = {sql_quote(document['category'])} "
            f"AND u.username = {sql_quote(document['owner'])};"
        )

    # documents.id was inserted explicitly, so the sequence must be advanced or
    # the next natural insert would collide with an existing id.
    lines += [
        "",
        "-- Realign the identity sequence after explicit id inserts",
        "SELECT setval(pg_get_serial_sequence('documents', 'id'), "
        "(SELECT MAX(id) FROM documents));",
        "",
        "-- Explicit READ grants, so permission filtering is visible in the demo",
    ]
    for permission in corpus.permissions:
        lines.append(
            "INSERT INTO document_permissions (document_id, user_id, permission_type) "
            f"SELECT {permission['document_id']}, u.id, {sql_quote(permission['permission_type'])} "
            f"FROM users u WHERE u.username = {sql_quote(permission['username'])};"
        )

    lines += ["", "COMMIT;", ""]
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def emit_mongo(corpus, path: Path, chunk_words: int, overlap_words: int) -> tuple[int, list[dict]]:
    """Write the MongoDB seed and return (chunk count, all chunk records)."""
    documents = []
    all_chunks: list[dict] = []

    for document in corpus.documents:
        chunks = chunk_document(
            {
                "doc_id": str(document["document_id"]),
                "title": document["title"],
                "text": document["body"],
                "language": document["language"],
                "source_dataset": "demo",
            },
            chunk_words=chunk_words,
            overlap_words=overlap_words,
        )
        for chunk in chunks:
            chunk["category"] = document["category"]
            chunk["department"] = document["department"]
            chunk["status"] = document["status"]
        all_chunks.extend(chunks)

        documents.append({
            "postgres_document_id": document["document_id"],
            "title": document["title"],
            "content": {
                "raw_text": document["body"],
                "language": document["language"],
                "word_count": document["word_count"],
                "character_count": document["character_count"],
            },
            "source": {
                "filename": f"{document['topic']}-{document['document_id']}."
                            f"{document['document_type'].lower()}",
                "mime_type": "application/octet-stream",
                "storage_type": "S3",
                "storage_reference": document["storage_reference"],
            },
            "metadata": {
                "authors": [document["owner"]],
                "keywords": document["keywords"],
                "department": document["department"],
            },
            "chunks": [
                {
                    "chunk_id": chunk["chunk_id"],
                    "text": chunk["text"],
                    "position": chunk["position"],
                    "page_number": chunk["position"] + 1,
                    "token_count": chunk["token_count"],
                }
                for chunk in chunks
            ],
            "references": [],
            "processing": {
                "status": "COMPLETED",
                "extractor_version": "demo-v1",
                "chunker_version": "v1.0",
            },
            "version": {
                "number": 1,
                "change_summary": "Demo corpus seed",
                "created_at": "__CURRENT_DATE_PLACEHOLDER__"
            },
        })

    body = json.dumps(documents, indent=1, ensure_ascii=False)
    body = body.replace('"__CURRENT_DATE_PLACEHOLDER__"', 'new Date("2026-09-12T00:00:00Z")')
    script = (
        "// Synthetic enterprise demo corpus.\n"
        "// DEMO ENVIRONMENT ONLY. Generated by subjects/ML/src/demo/emit.py.\n"
        "// Do not load into the integration test stack.\n\n"
        f"db.knowledge_documents.insertMany({body});\n"
    )
    path.write_text(script, encoding="utf-8", newline="\n")
    return len(all_chunks), all_chunks


def main() -> None:
    parser = argparse.ArgumentParser(description="Emit demo corpus seed files")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--per-topic", type=int, default=DEFAULT_PER_TOPIC)
    parser.add_argument("--chunk-words", type=int, default=180)
    parser.add_argument("--overlap-words", type=int, default=40)
    parser.add_argument("--out", default="../DBE-DSD/database/demo")
    parser.add_argument("--chunks-out", default="data/demo/chunks.json")
    args = parser.parse_args()

    corpus = generate(args.seed, args.per_topic)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    emit_postgres(corpus, out / "01-demo-seed.sql")
    chunk_count, chunks = emit_mongo(corpus, out / "01-demo-seed.js",
                                     args.chunk_words, args.overlap_words)

    chunks_path = Path(args.chunks_out)
    chunks_path.parent.mkdir(parents=True, exist_ok=True)
    chunks_path.write_text(json.dumps(chunks, indent=1, ensure_ascii=False), encoding="utf-8")

    print(f"documents   {len(corpus.documents)}")
    print(f"users       {len(corpus.users)}")
    print(f"permissions {len(corpus.permissions)}")
    print(f"chunks      {chunk_count}")
    print(f"postgres -> {(out / '01-demo-seed.sql').resolve()}")
    print(f"mongodb  -> {(out / '01-demo-seed.js').resolve()}")
    print(f"chunks   -> {chunks_path.resolve()}")


if __name__ == "__main__":
    main()
